### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Brain89** [rambler-digital-solutions/rambler-it-ios#1]
I'm a little bit confused about licensing this (and others) our open source project. Will we provide any?
P.S. Github rules to clarify https://help.github.com/articles/open-source-licensing/
P.P.S. And what about this?

```
//
//  ApplicationConfigurator.h
//  Conferences
//
//  Created by Karpushin Artem on 04/10/15.
//  Copyright © 2015 Rambler. All rights reserved.
//
```

**Comment by etolstoy** [comment]
We need @mogol in this thread.

I think of MIT as the simplest license available.

And headers are an important topic - we should choose one consistent style for our open-source products. Do you have any suggestions?

**Comment by mogol** [comment]
Lets use MIT.
Add license and change headers to http://opensource.org/licenses/MIT

**Comment by Brain89** [comment]
I agree MIT license would be the most appropriate choice. It is short and simple.

**Comment by Brain89** [comment]
I created PtR https://github.com/rambler-ios/RamblerConferences/pull/3

**Comment by Brain89** [comment]
@ArtemAK have a look at PtR 3

**Comment by Brain89** [comment]
@igrekde could you review this PtR?

**Comment by etolstoy** [comment]
@Brain89 Thanks for you contribution, the PR is merged!
