### ISSUE TITLE
Add design for "See other events" card on EventGalleryScreen

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/rambler-it-ios#101]

**Comment by ykamendrovskiy** [comment]
@etolstoy take a look. Added to Zeplin, btw
![seeotherevents](https://cloud.githubusercontent.com/assets/17292315/17747761/5534cce0-64c7-11e6-891d-f7e99c9f1026.png)

**Comment by etolstoy** [comment]
Seems nice, thanks!
