### ISSUE TITLE
Add a support for Taptic Engine

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/rambler-it-ios#126]
We should consider adding support for Haptic Feedback: https://developer.apple.com/ios/human-interface-guidelines/interaction/feedback/

**Comment by etolstoy** [comment]
https://developer.apple.com/reference/uikit/uifeedbackgenerator

**Comment by etolstoy** [comment]
So, what exactly we can do:
- EventGallery screen: Selection feedback on cards scroll.
- EventGallery screen: Failure notification when data is not loaded.
- RamblerLocation screen: Selection feedback on cards scroll.
- Search screen: Light impact on suggest select.

**Comment by suriksarkisyan** [comment]
[Done!](https://github.com/rambler-digital-solutions/rambler-it-ios/commit/535b7e5cf344318f74e1ce85f30f2523872e909a)
