### ISSUE TITLE
Как внедряется ServiceComponents

### ISSUE THREAD

**Issue by krasnodar95** [rambler-digital-solutions/rambler-it-ios#152]
Доброго времени суток. Я никак не могу понять где происходит внедрение объекта в поле serviceComponetns во все Assemblies всех модулей. Объясните данные момент

**Comment by suriksarkisyan** [comment]
@krasnodar95, `serviceComponents` является `property` родительской `assembly (ModuleAssemblyBase)`. И так как это `TyphoonAssembly`, и она уже активирована(в классе `TyphoonAppDelegate` все сразу активируются), то инициализировать её не надо. И если не вдаваться в подробности, то тайфуновские assembly не надо постоянно активировать(инициализировать), достаточно одного раза и затем просто в любом классе объявить её в `property` и она уже будет готова к использованию.
