### ISSUE TITLE
UberRides/UberRides.h issue

### ISSUE THREAD

**Issue by ilyarmnzhdn** [rambler-digital-solutions/rambler-it-ios#154]
'UberRides/UberRides.h' file not found UberRidesAssembly.h

**Comment by suriksarkisyan** [comment]
@ilyarmnzhdn sorry for this. You can fix it by Carthage installation.
You can use [Homebrew](http://brew.sh/) and install the Carthage tool on your system simply by running `brew update` and `brew install carthage`. (note: if you previously installed the binary version of Carthage, you should delete /Library/Frameworks/CarthageKit.framework).
Then just navigate to project folder in terminal and use `carthage update`
More info about Carthage installation you can find [here](https://github.com/Carthage/Carthage).

I will try to find some better fix for this.

**Comment by suriksarkisyan** [comment]
@ilyarmnzhdn from now you should only install `Carthage` on your Mac. No need to use `carthage update` more.

**Comment by ilyarmnzhdn** [comment]
@suriksarkisyan thank you! Issue is solved.
