### ISSUE TITLE
Crash in EventInteractor

### ISSUE THREAD

**Issue by ansinyutin** [rambler-digital-solutions/rambler-it-ios#159]
Xcode 8.2.1
iphone 5s ios 9.3 simulator
2017-01-29 21:11:24.472 Conferences[8779:171343] -[NSUserActivity setMapItem:]: unrecognized selector sent to instance 0x7fa942d0ca20
2017-01-29 21:11:24.522 Conferences[8779:171343] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSUserActivity setMapItem:]: unrecognized selector sent to instance 0x7fa942d0ca20'

*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106914d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010624adeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010691dd3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000106863cfa ___forwarding___ + 970
	4   CoreFoundation                      0x00000001068638a8 _CF_forwarding_prep_0 + 120
	5   Conferences                         0x0000000101ccf6fc -[EventInteractor registerUserActivityForEvent:] + 684
	6   Conferences                         0x0000000101cb940e -[EventPresenter didTriggerViewReadyEvent] + 462
	7   Conferences                         0x0000000101ce06ce -[EventViewController viewDidLoad] + 126
	8   UIKit                               0x000000010485d984 -[UIViewController loadViewIfRequired] + 1198
	9   UIKit                               0x000000010486393b -[UIViewController __viewWillAppear:] + 120
	10  UIKit                               0x0000000104893750 -[UINavigationController _startCustomTransition:] + 1203
	11  UIKit                               0x00000001048a3b9b -[UINavigationController _startDeferredTransitionIfNeeded:] + 712
	12  UIKit                               0x00000001048a4d0b -[UINavigationController __viewWillLayoutSubviews] + 57
	13  UIKit                               0x0000000104a53503 -[UILayoutContainerView layoutSubviews] + 248
	14  UIKit                               0x000000010477d980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
	15  QuartzCore                          0x0000000104434c00 -[CALayer layoutSublayers] + 146
	16  QuartzCore                          0x000000010442908e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	17  QuartzCore                          0x0000000104428f0c _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	18  QuartzCore                          0x000000010441d3c9 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
	19  QuartzCore                          0x000000010444b086 _ZN2CA11Transaction6commitEv + 486
	20  QuartzCore                          0x000000010444b7f8 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
	21  CoreFoundation                      0x0000000106839c37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	22  CoreFoundation                      0x0000000106839ba7 __CFRunLoopDoObservers + 391
	23  CoreFoundation                      0x000000010682f7fb __CFRunLoopRun + 1147
	24  CoreFoundation                      0x000000010682f0f8 CFRunLoopRunSpecific + 488
	25  GraphicsServices                    0x0000000109563ad2 GSEventRunModal + 161
	26  UIKit                               0x00000001046c2f09 UIApplicationMain + 171
	27  Conferences                         0x0000000101c9f428 main + 280
	28  libdyld.dylib                       0x000000010756792d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by suriksarkisyan** [comment]
@ansinyutin [fixed](https://github.com/rambler-digital-solutions/rambler-it-ios/commit/ef4561dffeddd2aa1c17cc4108f21478f3c290fb)!
