### ISSUE TITLE
Remove usage of private git repo

### ISSUE THREAD

**Issue by wiruzx** [rambler-digital-solutions/rambler-it-ios#2]
In the Podfile you currently have:

``` ruby
source 'https://gitlab.rambler.ru/cocoapods/cocoapods.git'
```

**Comment by etolstoy** [comment]
@wiruzx Hi, thanks for reporting!

We are working on this issue - currently you can build the project without running `pod install` - the `Pods` directory is included in the repo.

**Comment by ArtemAK** [comment]
The bug is fixed.
