### ISSUE TITLE
Design loading state for announcement and reports screens

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/rambler-it-ios#54]
This state will be visible during the first app launch.

**Comment by ykamendrovskiy** [comment]
@etolstoy that's it

![loading](https://cloud.githubusercontent.com/assets/17292315/17375563/91b8e652-59c2-11e6-8458-6fb8c0ad08ed.png)

**Comment by etolstoy** [comment]
Thanks!
