### ISSUE TITLE
Design no future events state for announcement screen

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/rambler-it-ios#55]
Linked to #9 .

**Comment by ykamendrovskiy** [comment]
@etolstoy The screen's got refactored and rebuilt from scratch. No-future-events state included

![slice](https://cloud.githubusercontent.com/assets/17292315/17249563/8bc7cb06-55b1-11e6-864b-7289bb5a1756.png)

**Comment by etolstoy** [comment]
We've just finished implementing this screen with the previous design version - migrating to the new one is very expensive. Is it possible to implement it in future versions?

**Comment by ykamendrovskiy** [comment]
@etolstoy yes, sure. Let's call it Stage 2

**Comment by etolstoy** [comment]
Great - but we still need this state for Stage 1.

**Comment by ykamendrovskiy** [comment]
@etolstoy hope that works
![nofuture](https://cloud.githubusercontent.com/assets/17292315/17375530/63e4889e-59c2-11e6-963f-dbd20f239c2c.png)

**Comment by etolstoy** [comment]
@ykamendrovskiy and where does this button lead?

**Comment by ykamendrovskiy** [comment]
@etolstoy it opens "Отчеты" tab

**Comment by etolstoy** [comment]
But it's an antipattern - to open other tabs using anything but tab bar itself. Maybe better remove it?

**Comment by ykamendrovskiy** [comment]
@etolstoy it might look a bit odd in certain cases, except when the only option is to show literally nothing. And I don't think it's an antipattern at all. Antipatterns mislead, or perform unpredictably and it's not this case. This case is about care, help and love.

If it's not difficult to implement I suggest doing it and performing a test-drive and a corridor testing. If people don't like it, fine, we'll remove it then

**Comment by etolstoy** [comment]
If you say, that it's all about love - than ok! :)

**Comment by etolstoy** [comment]
Just don't forget to export it in Zeplin.

**Comment by ykamendrovskiy** [comment]
done
