### ISSUE TITLE
Design speaker card screen

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/rambler-it-ios#57]

**Comment by ykamendrovskiy** [comment]
@etolstoy done
![speaker](https://cloud.githubusercontent.com/assets/17292315/17219042/f7b7f76c-54fa-11e6-90ad-642c6d123d2f.png)

**Comment by etolstoy** [comment]
Can Zeplin export these icons in all resolutions?

**Comment by ykamendrovskiy** [comment]
@etolstoy i'd better do it myself. But I wonder if the list is comlete

**Comment by etolstoy** [comment]
@ykamendrovskiy maybe we should also display all of the lectures by this speaker? Today I missed this feature a lot.
