### ISSUE TITLE
Design speaker and lecture cells for reports screen

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/rambler-it-ios#58]
These cells are visible in local search. You should also decide how we'll show tags.

**Comment by ykamendrovskiy** [comment]
@etolstoy why don't we show a separate section with tags as well in the results table?

**Comment by etolstoy** [comment]
And where would we go after tag tap? Looks like we need one more screen :)

**Comment by ykamendrovskiy** [comment]
@etolstoy search-by-tag-result-screen :-)

btw, are we having filters this release?

**Comment by etolstoy** [comment]
Yes, no filters yet. Can you also prepare design for tags screen? :)

**Comment by ykamendrovskiy** [comment]
@etolstoy search results cells + reports cells update. I changed my mind on the tags section for we already show all the events with the particular tag.

Do we have tags for both events and speakings?

first preview:
![reports](https://cloud.githubusercontent.com/assets/17292315/17366271/4c9bc156-599b-11e6-9e10-20d9fe5555b1.png)

**Comment by etolstoy** [comment]
Currently we have tags only for lectures. Tags for event are derived from all the lectures.

**Comment by ykamendrovskiy** [comment]
Fine, let's have this solution then 
![slice](https://cloud.githubusercontent.com/assets/17292315/17373288/99bf949a-59b8-11e6-9e53-6d2851da5861.png)

**Comment by ykamendrovskiy** [comment]
@etolstoy, And list by tag (accessed from detailed views). Seems done

![tag-list](https://cloud.githubusercontent.com/assets/17292315/17374199/852de0b4-59bc-11e6-822c-4425e8900b5b.png)

**Comment by etolstoy** [comment]
Great, thanks!
