### ISSUE TITLE
Export all icons in all resolutions

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/rambler-it-ios#63]
@ykamendrovskiy we need all of the icons in all resolutions: @1x, @2x, @3x.

**Comment by etolstoy** [comment]
We also need icons for video material type and other material type (Lecture screen).

**Comment by ykamendrovskiy** [comment]
"video material" isn't the lecture recording, is it? What sources are supported then? Youtube, Vimeo, anything else? I mean we can add icons for any of them, or some common video icon for all at once.

**Comment by etolstoy** [comment]
@ykamendrovskiy any of the sources - it's set up in the admin panel, so it's easier to add a common video icon.

**Comment by ykamendrovskiy** [comment]
@etolstoy both "video" and "uncpecified" icons added to Zepplin Cut artboard

**Comment by etolstoy** [comment]
@ykamendrovskiy New information on icons:
- Icon for "create route" on the location screen
- New tabbar icon for Search screen
- New tabbar icon for Events screen

**Comment by ykamendrovskiy** [comment]
@etolstoy done and added to "cut" artboard in Zeplin

**Comment by etolstoy** [comment]
Thanks!
