### ISSUE TITLE
Create new launch screens

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/rambler-it-ios#65]
We should prepare new launch screens.

**Comment by ykamendrovskiy** [comment]
@etolstoy лончскрин, состояние загрузки, ошибка загрузки

![loading](https://cloud.githubusercontent.com/assets/17292315/17647692/cdd1025c-620d-11e6-920c-6ccd645c1971.png)

[error1.mp4.zip](https://github.com/rambler-ios/RamblerConferences/files/416911/error1.mp4.zip)

**Comment by etolstoy** [comment]
Can you send me the gif of the error state?

**Comment by ykamendrovskiy** [comment]
@etolstoy try this one. If it's too big, I'll try to reduce the size
![giphy-20](https://cloud.githubusercontent.com/assets/17292315/17783471/435717d6-6589-11e6-9f40-3c431b948475.gif)

**Comment by etolstoy** [comment]
Great, thanks
